[project]
authors = []
build_dir = 'build'
cflags = []
cmake_version = '3.10'
compiler = 'g++'
include_dir = 'include'
lang = 'cpp'
lang_version = '20'
project_name = ''
project_version = '0.0.1'
src_dir = 'src'
[dependencies]
