[project]
name = "test-project"
cmake_version = "3.20.0"
compiler = "clang++"
authors = ["Cee Deez Nuts","Cock and ball torture"]
git = "https://github.com/cedeeznuts/test-project"
src_dir = "./src"
build_dir = "./build"
include_dir = "./include"
lang = "cpp"
langversion = "17"
[project.dependency.sdl2]
git="https:asljdkajsd"
version=""
