name: Clang-Format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ${{ secrets.CI_TOKEN }}

    - name: Install Clang-Format
      run: sudo apt-get install -y clang-format git

    - name: Run Clang-Format
      run: find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|hh\)' -exec clang-format -style=file -i {} \+

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply clang-format
        branch: ${{ github.head_ref }}
        file_pattern: .*\.(cpp|hpp|cc|cxx|h|hh)
        token: ${{ secrets.CI_TOKEN }}

